---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metaproject-zeus-api
  labels:
    app: metaproject-zeus-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metaproject-zeus-api
  template:
    metadata:
      labels:
        app: metaproject-zeus-api
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      containers:
        - name: api
          image: ghcr.io/adamvalalsky/metaproject-zeus/api:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: APPLICATION_MODE
              valueFrom:
                configMapKeyRef:
                  name: bootstrap
                  key: APPLICATION_MODE
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: database
                  key: HOST
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: database
                  key: NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-zeus
                  key: USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-zeus
                  key: PASSWORD
            - name: IDENTITY_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: identity
                  key: ISSUER
            - name: IDENTITY_CALLBACK_URL
              valueFrom:
                  configMapKeyRef:
                    name: identity
                    key: CALLBACK_URL
            - name: IDENTITY_CLIENT_ID
              valueFrom:
                  secretKeyRef:
                    name: identity-zeus
                    key: CLIENT_ID
            - name: IDENTITY_CLIENT_SECRET
              valueFrom:
                  secretKeyRef:
                    name: identity-zeus
                    key: CLIENT_SECRET
            - name: API_PUBLICATION_MAIL_TO
              value: "492900@mail.muni.cz"
            - name: FRONTEND_URL
              valueFrom:
                  configMapKeyRef:
                    name: gui
                    key: URL
            - name: REDOC_USERNAME
              valueFrom:
                  secretKeyRef:
                    name: redoc-zeus
                    key: USERNAME
            - name: REDOC_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: redoc-zeus
                    key: PASSWORD
            - name: CORS_ALLOW_ORIGIN
              valueFrom:
                  configMapKeyRef:
                    name: gui
                    key: URL
            - name: PERUN_URL
              valueFrom:
                  secretKeyRef:
                      name: perun-zeus
                      key: URL
            - name: PERUN_USER
              valueFrom:
                  secretKeyRef:
                      name: perun-zeus
                      key: USER
            - name: PERUN_PASSWORD
              valueFrom:
                  secretKeyRef:
                      name: perun-zeus
                      key: PASSWORD
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis
                  key: HOST
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: redis-zeus
                    key: PASS
            - name: FILE_UPLOAD_FOLDER
              value: "./uploads"
      imagePullSecrets:
        - name: regcred-zeus