apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

  - postgresql/claim.yaml
  - postgresql/deployment.yaml
  - postgresql/service.yaml

  - redis/claim.yaml
  - redis/deployment.yaml
  - redis/service.yaml

configMapGenerator:
  - name: bootstrap
    literals:
      - APPLICATION_MODE=production
  - name: database
    literals:
      - NAME=zeus
      - HOST=metaproject-zeus-postgres.valalsky-ns.svc.cluster.local
  - name: identity
    literals:
      - ISSUER=https://login.e-infra.cz/oidc
      - CALLBACK_URL=https://metaproject-zeus-api.dyn.cloud.e-infra.cz/auth/callback
  - name: gui
    literals:
      - URL=https://metaproject-zeus.dyn.cloud.e-infra.cz
  - name: redis
    literals:
      - HOST=metaproject-zeus-redis.valalsky-ns.svc.cluster.local
