version: "3.8"

services:
  nest-js-api:
    build:
      context: .
      dockerfile: api/docker/nest-js-dev/Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE_NODE}
    environment:
      - APPLICATION_MODE=development
    ports:
      - "3000:3000"
    volumes:
      - ./api/src:/app/src
      - ./api/package.json:/app/package.json
      - ./api/package-lock.json:/app/package-lock.json
    networks:
      common:
        aliases:
          - nestjs.resource-manager

networks:
  common:
    driver: bridge
