---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: metaproject-zeus-postgres-pvc
  labels:
    app: metaproject-zeus-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: nfs-csi
