---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: metaproject-zeus-redis-pvc
  labels:
    app: metaproject-zeus-redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi
