---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metaproject-zeus-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metaproject-zeus-redis
  template:
    metadata:
      labels:
        app: metaproject-zeus-redis
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      volumes:
        - name: redis-persistent-storage
          persistentVolumeClaim:
            claimName: metaproject-zeus-redis-pvc
      containers:
        - name: redis
          image: redis:7.4.0
          args: ["--requirepass", "$(REDIS_PASS)"]
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis-persistent-storage
              mountPath: /data
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: MASTER
              value: "true"
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: redis-zeus
                  key: PASS